git #!/bin/bash

# FIDO2-Node 测试框架快速参考卡
# Quick Reference Card for Unit Tests and Performance Tests

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           FIDO2-Node Test Framework - Quick Reference          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 UNIT TESTS (单元测试) - 快速安全性验证"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  运行所有单元测试:"
echo "    bash UT/run-unit-tests.sh all"
echo "    npm run test:unit"
echo ""
echo "  运行 SQL 注入防护测试:"
echo "    bash UT/run-unit-tests.sh sql-injection"
echo "    npm run test:sql-injection"
echo ""
echo "  运行函数集成测试:"
echo "    bash UT/run-unit-tests.sh functions"
echo "    npm run test:functions"
echo ""
echo "  测试覆盖范围: buildInClause, 参数化, 时间戳验证, 注入攻击防护"
echo ""

echo "⚡ PERFORMANCE TESTS (性能测试) - 系统能力评估"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  运行所有性能测试:"
echo "    bash UT/run-performance-tests.sh"
echo "    npm run test:performance"
echo ""
echo "  运行特定测试:"
echo "    node UT/register.performance.test.js"
echo "    node UT/authenticate.performance.test.js"
echo "    node UT/concurrency.performance.test.js"
echo ""
echo "  性能报告位置: UT/results/reports/"
echo ""

echo "🔄 COMBINED TESTING (综合测试)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  运行所有测试 (单元 + 性能):"
echo "    npm run test:all"
echo ""
echo "  测试覆盖率分析:"
echo "    npm run test:coverage"
echo ""

echo "📚 DOCUMENTATION (文档)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  完整测试框架指南:"
echo "    cat UT/README.md"
echo ""
echo "  框架概览总结:"
echo "    cat UT/TEST_FRAMEWORK_SUMMARY.md"
echo ""
echo "  SQL 注入漏洞修复详情:"
echo "    cat SQL_INJECTION_FIX_SUMMARY.md"
echo ""

echo "✅ VERIFICATION CHECKLIST (验证清单)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  代码修改后:"
echo "    [ ] bash UT/run-unit-tests.sh all"
echo ""
echo "  提交前:"
echo "    [ ] npm run test:coverage (检查覆盖率)"
echo "    [ ] 检查 SQL 查询是否已参数化"
echo ""
echo "  版本发布前:"
echo "    [ ] bash UT/run-unit-tests.sh all"
echo "    [ ] bash UT/run-performance-tests.sh"
echo "    [ ] 检查性能是否有回归"
echo ""

echo "🧪 TEST DETAILS (测试详情)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  单元测试包含:"
echo "    • SQL 注入漏洞修复验证 (40+ 用例)"
echo "    • 函数行为集成测试 (14+ 用例)"
echo "    • 边界情况和真实攻击场景"
echo ""
echo "  性能测试包含:"
echo "    • 注册流程性能 (preRegister, register)"
echo "    • 认证流程性能 (preAuthenticate, authenticate)"
echo "    • 并发能力 (10/25/50 并发)"
echo "    • 吞吐量和响应时间分布"
echo ""

echo "💡 TIPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • 使用 bash 脚本比 npm 更快"
echo "  • 单元测试应该在几秒内完成"
echo "  • 性能测试可能需要几十秒"
echo "  • 查看 results/ 目录获取详细性能报告"
echo ""

echo "🔒 SECURITY CHECK (安全检查)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  检查 SQL 注入修复:"
echo "    grep -n 'buildInClause' fido2-node/main.js"
echo "    grep -n 'SqlString.format' fido2-node/main.js"
echo ""
echo "  验证参数化 (不应包含动态拼接):"
echo "    grep -n \"'.*'+\" fido2-node/main.js"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  更多信息见: UT/README.md 和 UT/TEST_FRAMEWORK_SUMMARY.md      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
