#!/bin/bash
# =============================================================================
# fido2-node 应用部署脚本
# =============================================================================
# 参数:
#   $1  - 应用端口
#   $2  - PM2实例数
#   $3  - 存储类型 (mysql/mem)
#   $4  - 管理API令牌
#   $5  - 是否启用扩展 (true/false)
#   $6  - MySQL主机
#   $7  - 数据库名
#   $8  - 数据库用户
#   $9  - 数据库密码
#   $10 - 域名
# =============================================================================

set -e

APP_PORT=$1
INSTANCES=$2
STORAGE=$3
MNG_TOKEN=$4
ENABLE_EX=$5
MYSQL_HOST=$6
DB_NAME=$7
DB_USER=$8
DB_PASS=$9
DOMAIN=${10}

APP_DIR="/opt/fido2-node"
APP_EX_DIR="/opt/fido2-node-ex"

echo "=== 部署 fido2-node ==="

# 创建应用目录
sudo mkdir -p "$APP_DIR"
sudo chown -R ubuntu:ubuntu "$APP_DIR"
cd "$APP_DIR"

# 生成环境变量文件
echo "生成 .env 文件..."
cat << EOF > .env
# FIDO2 Node Server Configuration
# Generated by cluster-deploy.sh at $(date)

# Server
PORT=${APP_PORT}

# Storage
STORAGE=${STORAGE}

# MySQL
MYSQL_HOST=${MYSQL_HOST}
MYSQL_DATABASE=${DB_NAME}
MYSQL_USER=${DB_USER}
MYSQL_PASSWORD=${DB_PASS}
MYSQL_POOL_LIMIT=10
MYSQL_CONNECTION_TIMEOUT=10000

# FIDO2
FIDO_ORIGIN=https://fido2.${DOMAIN}
FIDO_RPID=fido2.${DOMAIN}

# Management API
MNG_API_TOKEN=${MNG_TOKEN}

# Extension
ENABLE_EX=${ENABLE_EX}
EOF

# 安装依赖
echo "安装npm依赖..."
npm install --production

# 如果启用扩展，也安装扩展依赖
if [[ "$ENABLE_EX" == "true" && -d "$APP_EX_DIR" ]]; then
    echo "安装扩展依赖..."
    cd "$APP_EX_DIR"
    if [[ -f "package.json" ]]; then
        npm install --production
    fi
    cd "$APP_DIR"
fi

# 复制PM2配置
if [[ -f /tmp/pm2-fido2-node.json ]]; then
    cp /tmp/pm2-fido2-node.json ./ecosystem.config.json
    
    # 更新实例数
    if [[ "$INSTANCES" != "max" ]]; then
        sed -i "s/\"instances\": \"max\"/\"instances\": $INSTANCES/" ./ecosystem.config.json
    fi
fi

# 创建日志目录
mkdir -p logs

# 停止现有进程（如果存在）
pm2 delete fido2-node 2>/dev/null || true

# 启动应用
echo "启动 fido2-node..."
if [[ -f ./ecosystem.config.json ]]; then
    pm2 start ecosystem.config.json
else
    pm2 start main.js --name fido2-node -i "$INSTANCES"
fi

# 保存PM2进程列表
pm2 save

# 配置PM2开机启动
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu 2>/dev/null || true

# 显示状态
echo ""
pm2 list

echo "=== fido2-node 部署完成 ==="
