#!/bin/bash
# =============================================================================
# fido2-portal 应用部署脚本
# =============================================================================
# 参数:
#   $1  - 应用端口
#   $2  - PM2实例数
#   $3  - Session密钥
#   $4  - Session超时(分钟)
#   $5  - MySQL主机
#   $6  - 数据库名
#   $7  - 数据库用户
#   $8  - 数据库密码
#   $9  - 域名
#   $10 - 管理API令牌
#   $11 - FIDO2 Worker URLs (逗号分隔)
# =============================================================================

set -e

APP_PORT=$1
INSTANCES=$2
SESSION_SECRET=$3
SESSION_TIMEOUT=$4
MYSQL_HOST=$5
DB_NAME=$6
DB_USER=$7
DB_PASS=$8
DOMAIN=$9
MNG_TOKEN=${10}
WORKER_URLS=${11}

APP_DIR="/opt/fido2-portal"

echo "=== 部署 fido2-portal ==="

cd "$APP_DIR"

# 生成环境变量文件
echo "生成 .env 文件..."
cat << EOF > .env
# FIDO2 Portal Configuration
# Generated by cluster-deploy.sh at $(date)

# Environment
NODE_ENV=production

# Server
PORT=${APP_PORT}
PORTAL_DOMAIN=portal.${DOMAIN}

# Session
SESSION_SECRET=${SESSION_SECRET}
SESSION_TIMEOUT_MINUTES=${SESSION_TIMEOUT}
SESSION_COOKIE_NAME=fido2_portal_session
SESSION_COOKIE_PATH=/

# MySQL
MYSQL_HOST=${MYSQL_HOST}
MYSQL_DATABASE=${DB_NAME}
MYSQL_USER=${DB_USER}
MYSQL_PASSWORD=${DB_PASS}
MYSQL_POOL_LIMIT=10

# FIDO2 Server
MNG_API_TOKEN=${MNG_TOKEN}
FIDO2_SERVER_URL=https://fido2.${DOMAIN}
FIDO2_WORKER_URLS=${WORKER_URLS}
EOF

# 安装依赖
echo "安装npm依赖..."
npm install --production

# 复制PM2配置
if [[ -f /tmp/pm2-fido2-portal.json ]]; then
    cp /tmp/pm2-fido2-portal.json ./ecosystem.config.json
    
    # 更新实例数
    if [[ "$INSTANCES" != "max" ]]; then
        sed -i "s/\"instances\": \"max\"/\"instances\": $INSTANCES/" ./ecosystem.config.json
    fi
fi

# 创建日志目录
mkdir -p logs

# 停止现有进程（如果存在）
pm2 delete fido2-portal 2>/dev/null || true

# 启动应用
echo "启动 fido2-portal..."
if [[ -f ./ecosystem.config.json ]]; then
    pm2 start ecosystem.config.json
else
    pm2 start app.js --name fido2-portal -i "$INSTANCES"
fi

# 保存PM2进程列表
pm2 save

# 显示状态
echo ""
pm2 list

echo "=== fido2-portal 部署完成 ==="
